service:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/showdata?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    

mybatis:
  typeAliasesPackage: com.xx.application.domain
  mapperLocations: classpath:mapper/*.xml  